default_stages: [pre-push]
repos:
- repo: local
  hooks:
    - id: make-lint
      name: "Run make lint"
      entry: make lint
      language: system
      pass_filenames: false
      stages: [pre-push]
    - id: make-dbml
      name: "Update database documentation"
      entry: make dbml
      language: system
      pass_filenames: false
      files: ^jolpica/formula_one/models/
      stages: [pre-push]